services:
  solo-ai:
    command: ["pnpm", "start:solo"]
    image: tj4q8cvba7f3jy53/solo-ai
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      - SERVER_PORT=3000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
    ports:
      - "3000:3000"
    restart: always
